// Generated by purs version 0.13.6
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Apply from "../Control.Apply/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad from "../Control.Monad/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
var Identity = function (x) {
    return x;
};
var newtypeIdentity = new Data_Newtype.Newtype(function (n) {
    return n;
}, Identity);
var functorIdentity = new Data_Functor.Functor(function (f) {
    return function (m) {
        return f(m);
    };
});
var applyIdentity = new Control_Apply.Apply(function ($dollar__unused) {
    return functorIdentity;
}, function (v) {
    return function (v1) {
        return v(v1);
    };
});
var bindIdentity = new Control_Bind.Bind(function ($dollar__unused) {
    return applyIdentity;
}, function (v) {
    return function (f) {
        return f(v);
    };
});
var applicativeIdentity = new Control_Applicative.Applicative(function ($dollar__unused) {
    return applyIdentity;
}, Identity);
var monadIdentity = new Control_Monad.Monad(function ($dollar__unused) {
    return applicativeIdentity;
}, function ($dollar__unused) {
    return bindIdentity;
});
export {
    Identity,
    newtypeIdentity,
    functorIdentity,
    applyIdentity,
    applicativeIdentity,
    bindIdentity,
    monadIdentity
};
