// Generated by purs version 0.13.6
var Alt = function (Functor0, alt) {
    this.Functor0 = Functor0;
    this.alt = alt;
};
var alt = function (dict) {
    return dict.alt;
};
export {
    Alt,
    alt
};
