// Generated by purs version 0.13.6
import * as React_Basic from "../React.Basic/index.js";
import * as React_Basic_DOM_Internal from "../React.Basic.DOM.Internal/index.js";
var ul$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("ul");
};
var ul = function (dictUnion) {
    return React_Basic.element(ul$prime());
};
var strong$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("strong");
};
var strong = function (dictUnion) {
    return React_Basic.element(strong$prime());
};
var strong_ = function (children) {
    return strong()({
        children: children
    });
};
var span$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("span");
};
var span = function (dictUnion) {
    return React_Basic.element(span$prime());
};
var section$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("section");
};
var section = function (dictUnion) {
    return React_Basic.element(section$prime());
};
var li$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("li");
};
var li = function (dictUnion) {
    return React_Basic.element(li$prime());
};
var li_ = function (children) {
    return li()({
        children: children
    });
};
var label$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("label");
};
var label = function (dictUnion) {
    return React_Basic.element(label$prime());
};
var input$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("input");
};
var input = function (dictUnion) {
    return React_Basic.element(input$prime());
};
var header$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("header");
};
var header = function (dictUnion) {
    return React_Basic.element(header$prime());
};
var h1$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h1");
};
var h1 = function (dictUnion) {
    return React_Basic.element(h1$prime());
};
var h1_ = function (children) {
    return h1()({
        children: children
    });
};
var footer$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("footer");
};
var footer = function (dictUnion) {
    return React_Basic.element(footer$prime());
};
var div$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("div");
};
var div = function (dictUnion) {
    return React_Basic.element(div$prime());
};
var button$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("button");
};
var button = function (dictUnion) {
    return React_Basic.element(button$prime());
};
var a$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("a");
};
var a = function (dictUnion) {
    return React_Basic.element(a$prime());
};
export {
    a,
    a$prime,
    button,
    button$prime,
    div,
    div$prime,
    footer,
    footer$prime,
    h1,
    h1$prime,
    h1_,
    header,
    header$prime,
    input,
    input$prime,
    label,
    label$prime,
    li,
    li$prime,
    li_,
    section,
    section$prime,
    span,
    span$prime,
    strong,
    strong$prime,
    strong_,
    ul,
    ul$prime
};
