// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var Semiring = function (add, mul, one, zero) {
    this.add = add;
    this.mul = mul;
    this.one = one;
    this.zero = zero;
};
var semiringInt = new Semiring($foreign.intAdd, $foreign.intMul, 1, 0);
var add = function (dict) {
    return dict.add;
};
export {
    Semiring,
    add,
    semiringInt
};
