// Generated by purs version 0.13.6
import * as Data_List_Types from "../Data.List.Types/index.js";
import * as Data_NonEmpty from "../Data.NonEmpty/index.js";
var singleton = (function () {
    var $76 = Data_NonEmpty.singleton(Data_List_Types.plusList);
    return function ($77) {
        return Data_List_Types.NonEmptyList($76($77));
    };
})();
export {
    singleton
};
