// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var Eq = function (eq) {
    this.eq = eq;
};
var eqString = new Eq($foreign.eqStringImpl);
var eqInt = new Eq($foreign.eqIntImpl);
var eqBoolean = new Eq($foreign.eqBooleanImpl);
var eq = function (dict) {
    return dict.eq;
};
var notEq = function (dictEq) {
    return function (x) {
        return function (y) {
            return eq(eqBoolean)(eq(dictEq)(x)(y))(false);
        };
    };
};
export {
    Eq,
    eq,
    notEq,
    eqBoolean,
    eqInt,
    eqString
};
