// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var Show = function (show) {
    this.show = show;
};
var showString = new Show($foreign.showStringImpl);
var showInt = new Show($foreign.showIntImpl);
var show = function (dict) {
    return dict.show;
};
export {
    Show,
    show,
    showInt,
    showString
};
