// Generated by purs version 0.13.6
var MonadThrow = function (Monad0, throwError) {
    this.Monad0 = Monad0;
    this.throwError = throwError;
};
var throwError = function (dict) {
    return dict.throwError;
};
export {
    throwError,
    MonadThrow
};
