// Generated by purs version 0.13.6
var classy = function (element) {
    return function (className) {
        return function (children) {
            return element({
                className: className,
                children: children
            });
        };
    };
};
export {
    classy
};
