// Generated by purs version 0.13.6
import * as Unsafe_Coerce from "../Unsafe.Coerce/index.js";
var unsafeCreateDOMComponent = Unsafe_Coerce.unsafeCoerce;
var css = Unsafe_Coerce.unsafeCoerce;
export {
    css,
    unsafeCreateDOMComponent
};
