// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var $$null = function (s) {
    return s === "";
};
export {
    toLower,
    trim,
    joinWith
} from "./foreign.js";
export {
    $$null as null
};
