// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
var toMaybe = function (n) {
    return $foreign.nullable(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
};
export {
    null,
    notNull
} from "./foreign.js";
export {
    toMaybe
};
