// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
var toMaybe = function (n) {
    return $foreign.nullable(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
};
var $$null = $foreign.jsNull;
export {
    notNull
} from "./foreign.js";
export {
    $$null as null,
    toMaybe
};
