// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var Semigroup = function (append) {
    this.append = append;
};
var semigroupString = new Semigroup($foreign.concatString);
var semigroupArray = new Semigroup($foreign.concatArray);
var append = function (dict) {
    return dict.append;
};
export {
    Semigroup,
    append,
    semigroupString,
    semigroupArray
};
