// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Semiring from "../Data.Semiring/index.js";
var Ring = function (Semiring0, sub) {
    this.Semiring0 = Semiring0;
    this.sub = sub;
};
var sub = function (dict) {
    return dict.sub;
};
var ringInt = new Ring(function ($dollar__unused) {
    return Data_Semiring.semiringInt;
}, $foreign.intSub);
export {
    Ring,
    sub,
    ringInt
};
