// Generated by purs version 0.13.6
import * as Control_Category from "../Control.Category/index.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Effect_Uncurried from "../Effect.Uncurried/index.js";
var EventFn = function (x) {
    return x;
};
var unsafeEventFn = EventFn;
var semigroupoidBuilder = Control_Semigroupoid.semigroupoidFn;
var handler_ = function ($190) {
    return Effect_Uncurried.mkEffectFn1(Data_Function["const"]($190));
};
var handler = function (v) {
    return function (cb) {
        return function ($191) {
            return cb(v($191))();
        };
    };
};
var categoryBuilder = Control_Category.categoryFn;
export {
    unsafeEventFn,
    handler,
    handler_,
    semigroupoidBuilder,
    categoryBuilder
};
