// Generated by purs version 0.13.6
import * as Control_Category from "../Control.Category/index.js";
var Bifunctor = function (bimap) {
    this.bimap = bimap;
};
var bimap = function (dict) {
    return dict.bimap;
};
var lmap = function (dictBifunctor) {
    return function (f) {
        return bimap(dictBifunctor)(f)(Control_Category.identity(Control_Category.categoryFn));
    };
};
export {
    bimap,
    Bifunctor,
    lmap
};
