// Generated by purs version 0.13.6
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
var Category = function (Semigroupoid0, identity) {
    this.Semigroupoid0 = Semigroupoid0;
    this.identity = identity;
};
var identity = function (dict) {
    return dict.identity;
};
var categoryFn = new Category(function ($dollar__unused) {
    return Control_Semigroupoid.semigroupoidFn;
}, function (x) {
    return x;
});
export {
    Category,
    identity,
    categoryFn
};
