// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
var Functor = function (map) {
    this.map = map;
};
var map = function (dict) {
    return dict.map;
};
var functorFn = new Functor(Control_Semigroupoid.compose(Control_Semigroupoid.semigroupoidFn));
var functorArray = new Functor($foreign.arrayMap);
export {
    Functor,
    map,
    functorFn,
    functorArray
};
