// Generated by purs version 0.13.6
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Monoid_Conj from "../Data.Monoid.Conj/index.js";
var Newtype = function (unwrap, wrap) {
    this.unwrap = unwrap;
    this.wrap = wrap;
};
var wrap = function (dict) {
    return dict.wrap;
};
var unwrap = function (dict) {
    return dict.unwrap;
};
var newtypeConj = new Newtype(function (v) {
    return v;
}, Data_Monoid_Conj.Conj);
var alaF = function (dictFunctor) {
    return function (dictFunctor1) {
        return function (dictNewtype) {
            return function (dictNewtype1) {
                return function (v) {
                    return function (f) {
                        var $147 = Data_Functor.map(dictFunctor1)(unwrap(dictNewtype1));
                        var $148 = Data_Functor.map(dictFunctor)(wrap(dictNewtype));
                        return function ($149) {
                            return $147(f($148($149)));
                        };
                    };
                };
            };
        };
    };
};
export {
    unwrap,
    wrap,
    Newtype,
    alaF,
    newtypeConj
};
