// Generated by purs version 0.13.6
var Apply = function (Functor0, apply) {
    this.Functor0 = Functor0;
    this.apply = apply;
};
var apply = function (dict) {
    return dict.apply;
};
export {
    Apply,
    apply
};
