// Generated by purs version 0.13.6
import * as Data_FoldableWithIndex from "../Data.FoldableWithIndex/index.js";
import * as Data_FunctorWithIndex from "../Data.FunctorWithIndex/index.js";
import * as Data_Traversable from "../Data.Traversable/index.js";
var TraversableWithIndex = function (FoldableWithIndex1, FunctorWithIndex0, Traversable2, traverseWithIndex) {
    this.FoldableWithIndex1 = FoldableWithIndex1;
    this.FunctorWithIndex0 = FunctorWithIndex0;
    this.Traversable2 = Traversable2;
    this.traverseWithIndex = traverseWithIndex;
};
var traverseWithIndexDefault = function (dictTraversableWithIndex) {
    return function (dictApplicative) {
        return function (f) {
            var $153 = Data_Traversable.sequence(dictTraversableWithIndex.Traversable2())(dictApplicative);
            var $154 = Data_FunctorWithIndex.mapWithIndex(dictTraversableWithIndex.FunctorWithIndex0())(f);
            return function ($155) {
                return $153($154($155));
            };
        };
    };
};
var traverseWithIndex = function (dict) {
    return dict.traverseWithIndex;
};
var traversableWithIndexArray = new TraversableWithIndex(function ($dollar__unused) {
    return Data_FoldableWithIndex.foldableWithIndexArray;
}, function ($dollar__unused) {
    return Data_FunctorWithIndex.functorWithIndexArray;
}, function ($dollar__unused) {
    return Data_Traversable.traversableArray;
}, function (dictApplicative) {
    return traverseWithIndexDefault(traversableWithIndexArray)(dictApplicative);
});
export {
    TraversableWithIndex,
    traverseWithIndex,
    traverseWithIndexDefault,
    traversableWithIndexArray
};
