// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Either from "../Data.Either/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Nullable from "../Data.Nullable/index.js";
import * as Simple_JSON from "../Simple.JSON/index.js";
var setItem = function (dictWriteForeign) {
    return function (key) {
        return function (val) {
            return function () {
                return $foreign.setItem_(key, Simple_JSON.writeJSON(dictWriteForeign)(val));
            };
        };
    };
};
var getItem = function (dictReadForeign) {
    return function (key) {
        return function __do() {
            var itemString = $foreign.getItem_(key);
            return Control_Bind.bindFlipped(Data_Maybe.bindMaybe)((function () {
                var $181 = Simple_JSON.readJSON(dictReadForeign);
                return function ($182) {
                    return Data_Either.hush($181($182));
                };
            })())(Data_Nullable.toMaybe(itemString));
        };
    };
};
export {
    setItem_,
    getItem_
} from "./foreign.js";
export {
    setItem,
    getItem
};
