// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
var $$null = function (xs) {
    return $foreign.length(xs) === 0;
};
export {
    length,
    cons,
    filter
} from "./foreign.js";
export {
    $$null as null
};
