// Generated by purs version 0.13.6
var Plus = function (Alt0, empty) {
    this.Alt0 = Alt0;
    this.empty = empty;
};
var empty = function (dict) {
    return dict.empty;
};
export {
    Plus,
    empty
};
