// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Control_Category from "../Control.Category/index.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
import * as Data_Symbol from "../Data.Symbol/index.js";
var Builder = function (x) {
    return x;
};
var semigroupoidBuilder = Control_Semigroupoid.semigroupoidFn;
var insert = function (dictCons) {
    return function (dictLacks) {
        return function (dictIsSymbol) {
            return function (l) {
                return function (a) {
                    return function (r1) {
                        return $foreign.unsafeInsert(Data_Symbol.reflectSymbol(dictIsSymbol)(l))(a)(r1);
                    };
                };
            };
        };
    };
};
var categoryBuilder = Control_Category.categoryFn;
var build = function (v) {
    return function (r1) {
        return v($foreign.copyRecord(r1));
    };
};
export {
    build,
    insert,
    semigroupoidBuilder,
    categoryBuilder
};
