// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Data_Functor from "../Data.Functor/index.js";
var FunctorWithIndex = function (Functor0, mapWithIndex) {
    this.Functor0 = Functor0;
    this.mapWithIndex = mapWithIndex;
};
var mapWithIndex = function (dict) {
    return dict.mapWithIndex;
};
var functorWithIndexArray = new FunctorWithIndex(function ($dollar__unused) {
    return Data_Functor.functorArray;
}, $foreign.mapWithIndexArray);
export {
    FunctorWithIndex,
    mapWithIndex,
    functorWithIndexArray
};
