// Generated by purs version 0.13.6
var Inl = (function () {
    function Inl(value0) {
        this.value0 = value0;
    };
    Inl.create = function (value0) {
        return new Inl(value0);
    };
    return Inl;
})();
var Inr = (function () {
    function Inr(value0) {
        this.value0 = value0;
    };
    Inr.create = function (value0) {
        return new Inr(value0);
    };
    return Inr;
})();
var NoArguments = (function () {
    function NoArguments() {

    };
    NoArguments.value = new NoArguments();
    return NoArguments;
})();
var Generic = function (from, to) {
    this.from = from;
    this.to = to;
};
var Constructor = function (x) {
    return x;
};
var to = function (dict) {
    return dict.to;
};
var from = function (dict) {
    return dict.from;
};
export {
    Generic,
    to,
    from,
    NoArguments,
    Inl,
    Inr,
    Constructor
};
