// Generated by purs version 0.13.6
import * as $foreign from "./foreign.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Apply from "../Control.Apply/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Control_Monad from "../Control.Monad/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
var monadEffect = new Control_Monad.Monad(function ($dollar__unused) {
    return applicativeEffect;
}, function ($dollar__unused) {
    return bindEffect;
});
var bindEffect = new Control_Bind.Bind(function ($dollar__unused) {
    return applyEffect;
}, $foreign.bindE);
var applyEffect = new Control_Apply.Apply(function ($dollar__unused) {
    return functorEffect;
}, Control_Monad.ap(monadEffect));
var applicativeEffect = new Control_Applicative.Applicative(function ($dollar__unused) {
    return applyEffect;
}, $foreign.pureE);
var functorEffect = new Data_Functor.Functor(Control_Applicative.liftA1(applicativeEffect));
export {
    functorEffect,
    applyEffect,
    applicativeEffect,
    bindEffect,
    monadEffect
};
